spring:
  profiles: dev
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configserver
      enabled: true 
  zipkin:
    discovery-client-enabled: true
    service:
      name: zipkin-server 
  boot:
    admin:
      client:
        username: "user"       #These two are needed so that the client
        password: "password"   #can register at the protected server api
        url:
        - ${ADMIN_SERVER_URL:http://172.16.4.58:9090/}
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://172.16.4.58:8761/eureka}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  hystrix:
    enabled: true
  okhttp:
    enabled: true
    

product-catalog:
  ribbon:
    eureka:
      enabled: true
    
    ServerListRefreshInterval: 15000
  
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
  
  # Max number of retries to all the servers (based on 'maxAutoRetriesNextServer' property, excluding the first try)
  maxAutoRetries: 3

  # Max number of next servers to retry (excluding the first server)
  maxAutoRetriesNextServer: 3

hystrix:
  shareSecurityContext: true

# Logging
logging:
  pattern:
    console: "[%-5level] %date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %logger{15}#%line %msg\n"
  level:
    root: TRACE
    com.training.mjunction.usersvcs: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    sun.rmi: ERROR
    org.reflections: ERROR
    sun.reflect: ERROR
    org.apache.coyote.http11: ERROR
    org.glassfish.jersey.internal.util: ERROR
    org.apache.tomcat.util.descriptor: ERROR
    org.apache.catalina.core: ERROR
    org.springframework.cloud.openfeign: TRACE
    com.netflix.loadbalancer: TRACE
    org.springframework.web.client: TRACE